blueprint:
  name: Auto Updates
  description: Provives automatic updates
  domain: automation
  input:
    update_entities_immediate:
      name: Update Entities (Immediate)
      description: The update entities to automatically update. These are updated as soon as an update is available.
      default: []
      selector:
        entity:
          filter:
            - domain:
                - update
          multiple: true
    update_entities_given_time:
      name: Update Entities (Given Time)
      description: The update entities to automatically update. These are updated at the update time given below.
      default: []
      selector:
        entity:
          filter:
            - domain:
                - update
          multiple: true
    update_time:
      name: Update Time
      description: The time at which updates will be completed
      default: 02:00:00
      selector:
        time: {}
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input update_entities_immediate
    id: update_entities_immediate
  - platform: time
    at: !input update_time
    id: update_time
condition: []
action:
  - choose:
    - conditions:
      - condition: trigger
        id: update_entities_immediate
      sequence:
      - repeat:
          for_each: !input update_entities_immediate
          sequence:
            - service: update.install
              continue_on_error: true
              target:
                entity_id: "{{ repeat.item }}"
    - conditions:
      - condition: trigger
        id: update_time
      sequence:
      - repeat:
          for_each: !input update_entities_given_time
          sequence:
            - service: update.install
              continue_on_error: true
              target:
                entity_id: "{{ repeat.item }}"
