blueprint:
  name: Charge Battery using EMHASS
  description: Run EMHASS Optimisation and Charge Battery.
  domain: automation
  input:
    battery_capacity:
      name: Battery Capacity
      description: The battery capacity sensor.
      selector:
        entity:
          filter:
            - domain:
                - sensor
    battery_power_charge:
      name: Battery Power Charge
      description: The power at which the battery is charging.
      selector:
        entity:
          filter:
            - domain:
                - input_number
    charge_battery:
      name: Charge Battery
      description: The button which starts charging the battery.
      selector:
        entity:
          filter:
            - domain:
                - input_button
    battery_control_time:
      name: Battery Control Time
      description: The battery control time.
      selector:
        entity:
          filter:
            - domain:
                - input_number
    hold_battery:
      name: Hold Battery
      description: The button which starts charging the battery.
      selector:
        entity:
          filter:
            - domain:
                - input_button
    emhass_p_batt_forecast:
      name: EMHASS P Batt Forecast
      description: The EMHASS P batt forecast entity.
      selector:
        entity:
          filter:
            - domain:
                - sensor
    emhass_p_grid_forecast:
      name: EMHASS P Grid Forecast
      description: The EMHASS P grid forecast entity.
      selector:
        entity:
          filter:
            - domain:
                - sensor
    publish_emhass_data:
      name: Publish EMHASS Data Action
      description: Action which publishises EMHASS Data.
      selector:
        action:
    run_emhass_optimisation:
      name: Run EMHASS Optimisation Action
      description: Action which runs EMHASS Optimisation.
      selector:
        action:
  source_url: https://github.com/Excentyl/ha-blueprints/blob/main/charge_battery_using_emhass.yaml
variables:
  battery_capacity_var: !input battery_capacity
  battery_power_charge_var: !input battery_power_charge
  emhass_p_batt_forecast_var: !input emhass_p_batt_forecast
  emhass_p_grid_forecast_var: !input emhass_p_grid_forecast
mode: single
max_exceeded: silent
triggers:
  - trigger: time_pattern
    minutes: /30
conditions: []
actions:
  - if:
      - condition: template
        value_template: "{{ true }}"
    then: !input run_emhass_optimisation
  - if:
      - condition: template
        value_template: "{{ true }}"
    then: !input publish_emhass_data
  - variables:
      battery_forecast_charge: >-
        {{ -min(states(emhass_p_batt_forecast_var) | float, 0) }}
      battery_hold: >-
        {{ states(emhass_p_grid_forecast_var) | float > 0 and states(emhass_p_batt_forecast_var) | float == 0 }}
      time_until_next_slot: >-
        {{ (as_timestamp(state_attr(emhass_p_batt_forecast_var, 'battery_scheduled_power')[1]['date']) - as_timestamp(now())) | round }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ battery_hold }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: !input battery_control_time
            data:
              value: "{{ time_until_next_slot }}"
          - action: input_button.press
            target:
              entity_id: !input hold_battery
            data: {}
      - conditions:
          - condition: template
            value_template: "{{ states(emhass_p_grid_forecast_var) | float > 0 and battery_forecast_charge > 0 }}"
        sequence:
          - variables:
              battery_power_charge: >-
                {{ state_attr(battery_power_charge_var, 'max') }}
              battery_control_time: >-
                {{ time_until_next_slot * min(battery_forecast_charge / battery_power_charge, 1) }}
          - action: input_number.set_value
            target:
              entity_id: input_number.solar_battery_control_time
            data:
              value: "{{ battery_control_time }}"
          - action: input_number.set_value
            metadata: {}
            data:
              value: "{{ battery_power_charge }}"
            target:
              entity_id: !input battery_power_charge
          - action: input_button.press
            target:
              entity_id: !input charge_battery
            data: {}
