blueprint:
  name: Watchman Report Notification
  description: Creates a persistent notificaion if any issues are detected in a watchman report.
  domain: automation
  input:
    watchman_missing_entities:
      name: Watchman Missing Entities
      description: The missing entities entity provided by Watchman.
      selector:
        entity:
          filter:
            - integration: watchman
          multiple: false
    watchman_missing_actions:
      name: Watchman Missing Actions
      description: The missing actions entity provided by Watchman.
      selector:
        entity:
          filter:
            - integration: watchman
          multiple: false
    watchman_notification_id:
      name: Watchman Notification ID
      description: The notification ID of the persistent notification
      default: watchman_report
      selector:
        text:
  source_url: https://github.com/Excentyl/ha-blueprints/blob/main/watchman_report_notification.yaml
mode: queued
max: 10
trigger:
  - platform: state
    entity_id:
      - !input watchman_missing_entities
      - !input watchman_missing_actions
condition: []
action:
  - if:
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: !input watchman_missing_entities
            above: 0
          - condition: numeric_state
            entity_id: !input watchman_missing_actions
            above: 0
    then:
      - action: watchman.report
        data:
          action: persistent_notification.create
          data:
            notification_id: !input watchman_notification_id
          create_file: false
    else:
      - action: persistent_notification.dismiss
        metadata: {}
        data:
          notification_id: !input watchman_notification_id
